language: cpp
dist: trusty

git:
  submodules: false

script:
  - cd ../..
  - git clone https://github.com/qt/qt5 Qt && cd Qt
  - perl init-repository --module-subset=qtbase,qtlocation,qtdeclarative
  - ./configure -prefix $PWD/qtbase -opensource -nomake tests -nomake examples -confirm-license -release
  - travis_wait 200 make -j 4 --silent
